// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAMzYuCnMgJQxtq9Wuso0kYdwjm1mOBwg',
    appId: '1:179494741037:web:d3fb48a88c840cb41b44a4',
    messagingSenderId: '179494741037',
    projectId: 'app2go-c5bbe',
    authDomain: 'app2go-c5bbe.firebaseapp.com',
    storageBucket: 'app2go-c5bbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Lv26fsL9imsA6yasyDXX0csp2iLOAlw',
    appId: '1:179494741037:android:e7d1e58570786fb41b44a4',
    messagingSenderId: '179494741037',
    projectId: 'app2go-c5bbe',
    storageBucket: 'app2go-c5bbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-3GNqk8RZDFCLmSguak8cewum86VuNcY',
    appId: '1:179494741037:ios:1330be5ff97fceb71b44a4',
    messagingSenderId: '179494741037',
    projectId: 'app2go-c5bbe',
    storageBucket: 'app2go-c5bbe.appspot.com',
    iosClientId: '179494741037-9td90autmpb8vj27utlata8im955e3ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2go',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-3GNqk8RZDFCLmSguak8cewum86VuNcY',
    appId: '1:179494741037:ios:1330be5ff97fceb71b44a4',
    messagingSenderId: '179494741037',
    projectId: 'app2go-c5bbe',
    storageBucket: 'app2go-c5bbe.appspot.com',
    iosClientId: '179494741037-9td90autmpb8vj27utlata8im955e3ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2go',
  );
}
